config/routes.rb
Rails.application.routes.draw do

  resources :administrators
  resources :line_items
  resources :orders
  resources :discount_items
  resources :users
  root 'static_pages#index'
  get '/signup' => 'users#new'
  resources :products
  resources :sessions
  get 'login' => "sessions#new"

end

app/models/discount_item.rb
class DiscountItem < ActiveRecord::Base
  belongs_to :product
end

app/controllers/discount_items_controller.rb
class DiscountItemsController < ApplicationController
  before_action :set_discount_item, only: [:show, :edit, :update, :destroy]

  # GET /discount_items
  # GET /discount_items.json
  def index
    @discount_items = DiscountItem.all
  end

  # GET /discount_items/1
  # GET /discount_items/1.json
  def show
  end

  # GET /discount_items/new
  def new
    @discount_item = DiscountItem.new
  end

  # GET /discount_items/1/edit
  def edit
  end

  # POST /discount_items
  # POST /discount_items.json
  def create
    @discount_item = DiscountItem.new(discount_item_params)

    respond_to do |format|
      if @discount_item.save
        format.html { redirect_to @discount_item, notice: 'Discount item was successfully created.' }
        format.json { render :show, status: :created, location: @discount_item }
      else
        format.html { render :new }
        format.json { render json: @discount_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discount_items/1
  # PATCH/PUT /discount_items/1.json
  def update
    respond_to do |format|
      if @discount_item.update(discount_item_params)
        format.html { redirect_to @discount_item, notice: 'Discount item was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount_item }
      else
        format.html { render :edit }
        format.json { render json: @discount_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discount_items/1
  # DELETE /discount_items/1.json
  def destroy
    @discount_item.destroy
    respond_to do |format|
      format.html { redirect_to discount_items_url, notice: 'Discount item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount_item
      @discount_item = DiscountItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_item_params
      params.require(:discount_item).permit(:product_id, :discount)
    end
end

app/helpers/discount_items_helper.rb
module DiscountItemsHelper
end

app/views/discount_items/_form.html.erb
<%= form_for(@discount_item) do |f| %>
  <% if @discount_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discount_item.errors.count, "error") %> prohibited this discount_item from being saved:</h2>

      <ul>
      <% @discount_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.select :product_id, Product.all.collect { |c| [ c.title, c.id ] } %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.number_field :discount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discount_items/edit.html.erb
<h1>Editing Discount Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @discount_item %> |
<%= link_to 'Back', discount_items_path %>

app/views/discount_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Discount Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Discount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discount_items.each do |discount_item| %>
      <tr>
        <td><%= discount_item.product.title %></td>
        <td><%= discount_item.discount %></td>
        <td><%= link_to 'Show', discount_item %></td>
        <td><%= link_to 'Edit', edit_discount_item_path(discount_item) %></td>
        <td><%= link_to 'Destroy', discount_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discount item', new_discount_item_path %>

app/views/discount_items/new.html.erb
<h1>New Discount Item</h1>

<%= render 'form' %>

<%= link_to 'Back', discount_items_path %>

app/views/discount_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discount:</strong>
  <%= @discount_item.discount %>
</p>

<%= link_to 'Edit', edit_discount_item_path(@discount_item) %> |
<%= link_to 'Back', discount_items_path %>