config/routes.rb
Rails.application.routes.draw do

  resources :administrators
  resources :line_items
  resources :orders
  resources :discount_items
  resources :users
  root 'static_pages#index'
  get '/signup' => 'users#new'
  resources :products
  resources :sessions
  get 'login' => "sessions#new"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :order, dependent: :destroy
  has_one :administrator, dependent: :destroy

  def admin?
    unless self.administrator == nil
      true
    end
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.order = Order.create

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= notice %>
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%total_price = 0 %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<h2>Заказ:</h2>
<table>
  <th>Название продукта</th>
  <th>Стоимость</th>
  <% @user.order.line_items.each do |item| %>
  <tr>
    <td><%= link_to item.product.title, item.product %></td>
    <td><%= item.product.price %></td>
    <% total_price += item.product.price %>
    <td><%= link_to "Удалить", item, method: :delete , data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <% end %>
</table>
<strong>Стоимость всего заказа: <%= total_price %></strong><br>
<div class="status"><strong>Статус:</strong> <%= @user.order.status %></div>
<%if @user.order.status == "Не подтвержден" %>
    <div class="button success"> <%= link_to "Подтвердить", order_path(:order => {status: "Подтвержден"}, id: @user.order.id), method: :put %> </div>
<%else %>
    <div class="button alert">  <%= link_to "Отменить", order_path(:order => {status: "Не подтвержден"}, id: @user.order.id), method: :put %></div>
<%end  %>

<div class="links"> <%= link_to 'Edit', edit_user_path(@user) %>|
  <%= link_to 'Back', users_path %> </div>